describe ("Register tests", () => {
    it('Visit gallery', () => {
        cy.visit('https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').eq(2).click()
    })
    it('Register with valid credentials', () => {
        cy.visit('https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('cyName')
        cy.get('#last-name').type('cylastName')
        cy.get('#email').type('testcy@gmail.com')
        cy.get('#password').type('cyTest12345')
        cy.get('#password-confirmation').type('cyTest12345')
        cy.get('.form-check-input').click()
        cy.get('button[type=submit]').click()
    })
    it('Register with invalid email', () => {
        cy.visit('https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('cyName')
        cy.get('#last-name').type('cylastName')
        cy.get('#email').type('testcy@gmail.c')
        cy.get('#password').type('cyTest12345')
        cy.get('#password-confirmation').type('cyTest12345')
        cy.get('.form-check-input').click()
        cy.get('button[type=submit]').click()
    })
    it('Register with invalid password, less then 8 char', () => {
        cy.visit('https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('cyName')
        cy.get('#last-name').type('cylastName')
        cy.get('#email').type('testcy02@gmail.com')
        cy.get('#password').type('cyTest')
        cy.get('#password-confirmation').type('cyTest')
        cy.get('.form-check-input').click()
        cy.get('button[type=submit]').click()
    })
    it('Register without first name', () => {
        cy.visit('https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').should('have.value', '');
        cy.get('#last-name').type('cylastName')
        cy.get('#email').type('testcy03@gmail.com')
        cy.get('#password').type('cyTest112233')
        cy.get('#password-confirmation').type('cyTest112233')
        cy.get('.form-check-input').click()
        cy.get('button[type=submit]').click()
    })
    it('Register without last name', () => {
        cy.visit('https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('cyName')
        cy.get('#last-name').should('have.value', '')
        cy.get('#email').type('testcy04@gmail.com')
        cy.get('#password').type('cyTest112233')
        cy.get('#password-confirmation').type('cyTest112233')
        cy.get('.form-check-input').click()
        cy.get('button[type=submit]').click()
    })
    it('Register without accepted terms', () => {
        cy.visit('https://gallery-app.vivifyideas.com/')
        cy.get('.nav-link').eq(2).click()
        cy.get('#first-name').type('cyName')
        cy.get('#last-name').type('cylastName')
        cy.get('#email').type('testcy04@gmail.com')
        cy.get('#password').type('cyTest112233')
        cy.get('#password-confirmation').type('cyTest112233')
        //cy.get('.form-check-input').click()
        cy.get('button[type=submit]').click()
    })

})